//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace EFSAMessageCreator_Pesticides {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class message {
        
        private object headerField;
        
        private payload payloadField;
        
        /// <remarks/>
        public object header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public payload payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSDRepeatableType {
        
        private string[] valueField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSDCompoundType {
        
        private string baseField;
        
        private SSDCompoundTypeValue[] valueField;
        
        private string[] textField;
        
        /// <remarks/>
        public string @base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public SSDCompoundTypeValue[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SSDCompoundTypeValue {
        
        private string codeField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class payload {
        
        private object operationField;
        
        private result[] datasetField;
        
        /// <remarks/>
        public object operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public result[] dataset {
            get {
                return this.datasetField;
            }
            set {
                this.datasetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class result {
        
        private string resEvaluationField;
        
        private string anMethTextField;
        
        private string analysisYField;
        
        private string sampAreaField;
        
        private string labCodeField;
        
        private string labSampCodeField;
        
        private decimal moistPercField;
        
        private bool moistPercFieldSpecified;
        
        private string paramTextField;
        
        private decimal lotSizeField;
        
        private bool lotSizeFieldSpecified;
        
        private decimal resLegalLimitField;
        
        private bool resLegalLimitFieldSpecified;
        
        private string expiryDField;
        
        private string prodPackField;
        
        private string procAreaField;
        
        private string lotSizeUnitField;
        
        private string paramCodeField;
        
        private string analysisDField;
        
        private string progCodeField;
        
        private string prodComField;
        
        private string localOrgField;
        
        private decimal resValField;
        
        private bool resValFieldSpecified;
        
        private string analysisMField;
        
        private string sampYField;
        
        private string anMethRefCodeField;
        
        private decimal resLODField;
        
        private bool resLODFieldSpecified;
        
        private string sampPointField;
        
        private string resUnitField;
        
        private decimal cCbetaField;
        
        private bool cCbetaFieldSpecified;
        
        private string labCountryField;
        
        private string eFSAParamCodeField;
        
        private string origCountryField;
        
        private string procCountryField;
        
        private string prodMField;
        
        private string labAccredField;
        
        private string prodYField;
        
        private decimal resValUncertField;
        
        private bool resValUncertFieldSpecified;
        
        private string paramTypeField;
        
        private string sampCountryField;
        
        private string prodIngredField;
        
        private string exprResField;
        
        private string anMethCodeField;
        
        private decimal cCalphaField;
        
        private bool cCalphaFieldSpecified;
        
        private string resultCodeField;
        
        private SSDRepeatableType actTakenCodeField;
        
        private string progSampStrategyField;
        
        private string prodDField;
        
        private string origAreaField;
        
        private string prodCodeField;
        
        private decimal fatPercField;
        
        private bool fatPercFieldSpecified;
        
        private string sampMField;
        
        private string progLegalRefField;
        
        private string resLegalLimitTypeField;
        
        private string prodTreatField;
        
        private string prodBrandNameField;
        
        private string sampMethodField;
        
        private string resTypeField;
        
        private string sampleNumField;
        
        private string localOrgCountryField;
        
        private string expiryMField;
        
        private string prodProdMethField;
        
        private string prodTextField;
        
        private decimal resValUncertSDField;
        
        private bool resValUncertSDFieldSpecified;
        
        private string origFishAreaCodeField;
        
        private string resQualValueField;
        
        private string resCommField;
        
        private string expiryYField;
        
        private string langField;
        
        private string resValRecCorrField;
        
        private decimal resLOQField;
        
        private string labSubSampCodeField;
        
        private string progTypeField;
        
        private string accredProcField;
        
        private decimal resValRecField;
        
        private bool resValRecFieldSpecified;
        
        private string sampDField;
        
        private string eFSAProdCodeField;
        
        private string prodManufField;
        
        private string origFishAreaTextField;
        
        private string amTypeField;
        
        /// <remarks/>
        public string resEvaluation {
            get {
                return this.resEvaluationField;
            }
            set {
                this.resEvaluationField = value;
            }
        }
        
        /// <remarks/>
        public string anMethText {
            get {
                return this.anMethTextField;
            }
            set {
                this.anMethTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string analysisY {
            get {
                return this.analysisYField;
            }
            set {
                this.analysisYField = value;
            }
        }
        
        /// <remarks/>
        public string sampArea {
            get {
                return this.sampAreaField;
            }
            set {
                this.sampAreaField = value;
            }
        }
        
        /// <remarks/>
        public string labCode {
            get {
                return this.labCodeField;
            }
            set {
                this.labCodeField = value;
            }
        }
        
        /// <remarks/>
        public string labSampCode {
            get {
                return this.labSampCodeField;
            }
            set {
                this.labSampCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal moistPerc {
            get {
                return this.moistPercField;
            }
            set {
                this.moistPercField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moistPercSpecified {
            get {
                return this.moistPercFieldSpecified;
            }
            set {
                this.moistPercFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string paramText {
            get {
                return this.paramTextField;
            }
            set {
                this.paramTextField = value;
            }
        }
        
        /// <remarks/>
        public decimal lotSize {
            get {
                return this.lotSizeField;
            }
            set {
                this.lotSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lotSizeSpecified {
            get {
                return this.lotSizeFieldSpecified;
            }
            set {
                this.lotSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal resLegalLimit {
            get {
                return this.resLegalLimitField;
            }
            set {
                this.resLegalLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resLegalLimitSpecified {
            get {
                return this.resLegalLimitFieldSpecified;
            }
            set {
                this.resLegalLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string expiryD {
            get {
                return this.expiryDField;
            }
            set {
                this.expiryDField = value;
            }
        }
        
        /// <remarks/>
        public string prodPack {
            get {
                return this.prodPackField;
            }
            set {
                this.prodPackField = value;
            }
        }
        
        /// <remarks/>
        public string procArea {
            get {
                return this.procAreaField;
            }
            set {
                this.procAreaField = value;
            }
        }
        
        /// <remarks/>
        public string lotSizeUnit {
            get {
                return this.lotSizeUnitField;
            }
            set {
                this.lotSizeUnitField = value;
            }
        }
        
        /// <remarks/>
        public string paramCode {
            get {
                return this.paramCodeField;
            }
            set {
                this.paramCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string analysisD {
            get {
                return this.analysisDField;
            }
            set {
                this.analysisDField = value;
            }
        }
        
        /// <remarks/>
        public string progCode {
            get {
                return this.progCodeField;
            }
            set {
                this.progCodeField = value;
            }
        }
        
        /// <remarks/>
        public string prodCom {
            get {
                return this.prodComField;
            }
            set {
                this.prodComField = value;
            }
        }
        
        /// <remarks/>
        public string localOrg {
            get {
                return this.localOrgField;
            }
            set {
                this.localOrgField = value;
            }
        }
        
        /// <remarks/>
        public decimal resVal {
            get {
                return this.resValField;
            }
            set {
                this.resValField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValSpecified {
            get {
                return this.resValFieldSpecified;
            }
            set {
                this.resValFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string analysisM {
            get {
                return this.analysisMField;
            }
            set {
                this.analysisMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sampY {
            get {
                return this.sampYField;
            }
            set {
                this.sampYField = value;
            }
        }
        
        /// <remarks/>
        public string anMethRefCode {
            get {
                return this.anMethRefCodeField;
            }
            set {
                this.anMethRefCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal resLOD {
            get {
                return this.resLODField;
            }
            set {
                this.resLODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resLODSpecified {
            get {
                return this.resLODFieldSpecified;
            }
            set {
                this.resLODFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string sampPoint {
            get {
                return this.sampPointField;
            }
            set {
                this.sampPointField = value;
            }
        }
        
        /// <remarks/>
        public string resUnit {
            get {
                return this.resUnitField;
            }
            set {
                this.resUnitField = value;
            }
        }
        
        /// <remarks/>
        public decimal CCbeta {
            get {
                return this.cCbetaField;
            }
            set {
                this.cCbetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CCbetaSpecified {
            get {
                return this.cCbetaFieldSpecified;
            }
            set {
                this.cCbetaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string labCountry {
            get {
                return this.labCountryField;
            }
            set {
                this.labCountryField = value;
            }
        }
        
        /// <remarks/>
        public string EFSAParamCode {
            get {
                return this.eFSAParamCodeField;
            }
            set {
                this.eFSAParamCodeField = value;
            }
        }
        
        /// <remarks/>
        public string origCountry {
            get {
                return this.origCountryField;
            }
            set {
                this.origCountryField = value;
            }
        }
        
        /// <remarks/>
        public string procCountry {
            get {
                return this.procCountryField;
            }
            set {
                this.procCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string prodM {
            get {
                return this.prodMField;
            }
            set {
                this.prodMField = value;
            }
        }
        
        /// <remarks/>
        public string labAccred {
            get {
                return this.labAccredField;
            }
            set {
                this.labAccredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string prodY {
            get {
                return this.prodYField;
            }
            set {
                this.prodYField = value;
            }
        }
        
        /// <remarks/>
        public decimal resValUncert {
            get {
                return this.resValUncertField;
            }
            set {
                this.resValUncertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValUncertSpecified {
            get {
                return this.resValUncertFieldSpecified;
            }
            set {
                this.resValUncertFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string paramType {
            get {
                return this.paramTypeField;
            }
            set {
                this.paramTypeField = value;
            }
        }
        
        /// <remarks/>
        public string sampCountry {
            get {
                return this.sampCountryField;
            }
            set {
                this.sampCountryField = value;
            }
        }
        
        /// <remarks/>
        public string prodIngred {
            get {
                return this.prodIngredField;
            }
            set {
                this.prodIngredField = value;
            }
        }
        
        /// <remarks/>
        public string exprRes {
            get {
                return this.exprResField;
            }
            set {
                this.exprResField = value;
            }
        }
        
        /// <remarks/>
        public string anMethCode {
            get {
                return this.anMethCodeField;
            }
            set {
                this.anMethCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal CCalpha {
            get {
                return this.cCalphaField;
            }
            set {
                this.cCalphaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CCalphaSpecified {
            get {
                return this.cCalphaFieldSpecified;
            }
            set {
                this.cCalphaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDRepeatableType actTakenCode {
            get {
                return this.actTakenCodeField;
            }
            set {
                this.actTakenCodeField = value;
            }
        }
        
        /// <remarks/>
        public string progSampStrategy {
            get {
                return this.progSampStrategyField;
            }
            set {
                this.progSampStrategyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string prodD {
            get {
                return this.prodDField;
            }
            set {
                this.prodDField = value;
            }
        }
        
        /// <remarks/>
        public string origArea {
            get {
                return this.origAreaField;
            }
            set {
                this.origAreaField = value;
            }
        }
        
        /// <remarks/>
        public string prodCode {
            get {
                return this.prodCodeField;
            }
            set {
                this.prodCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal fatPerc {
            get {
                return this.fatPercField;
            }
            set {
                this.fatPercField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fatPercSpecified {
            get {
                return this.fatPercFieldSpecified;
            }
            set {
                this.fatPercFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sampM {
            get {
                return this.sampMField;
            }
            set {
                this.sampMField = value;
            }
        }
        
        /// <remarks/>
        public string progLegalRef {
            get {
                return this.progLegalRefField;
            }
            set {
                this.progLegalRefField = value;
            }
        }
        
        /// <remarks/>
        public string resLegalLimitType {
            get {
                return this.resLegalLimitTypeField;
            }
            set {
                this.resLegalLimitTypeField = value;
            }
        }
        
        /// <remarks/>
        public string prodTreat {
            get {
                return this.prodTreatField;
            }
            set {
                this.prodTreatField = value;
            }
        }
        
        /// <remarks/>
        public string prodBrandName {
            get {
                return this.prodBrandNameField;
            }
            set {
                this.prodBrandNameField = value;
            }
        }
        
        /// <remarks/>
        public string sampMethod {
            get {
                return this.sampMethodField;
            }
            set {
                this.sampMethodField = value;
            }
        }
        
        /// <remarks/>
        public string resType {
            get {
                return this.resTypeField;
            }
            set {
                this.resTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sampleNum {
            get {
                return this.sampleNumField;
            }
            set {
                this.sampleNumField = value;
            }
        }
        
        /// <remarks/>
        public string localOrgCountry {
            get {
                return this.localOrgCountryField;
            }
            set {
                this.localOrgCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string expiryM {
            get {
                return this.expiryMField;
            }
            set {
                this.expiryMField = value;
            }
        }
        
        /// <remarks/>
        public string prodProdMeth {
            get {
                return this.prodProdMethField;
            }
            set {
                this.prodProdMethField = value;
            }
        }
        
        /// <remarks/>
        public string prodText {
            get {
                return this.prodTextField;
            }
            set {
                this.prodTextField = value;
            }
        }
        
        /// <remarks/>
        public decimal resValUncertSD {
            get {
                return this.resValUncertSDField;
            }
            set {
                this.resValUncertSDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValUncertSDSpecified {
            get {
                return this.resValUncertSDFieldSpecified;
            }
            set {
                this.resValUncertSDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string origFishAreaCode {
            get {
                return this.origFishAreaCodeField;
            }
            set {
                this.origFishAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string resQualValue {
            get {
                return this.resQualValueField;
            }
            set {
                this.resQualValueField = value;
            }
        }
        
        /// <remarks/>
        public string resComm {
            get {
                return this.resCommField;
            }
            set {
                this.resCommField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string expiryY {
            get {
                return this.expiryYField;
            }
            set {
                this.expiryYField = value;
            }
        }
        
        /// <remarks/>
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public string resValRecCorr {
            get {
                return this.resValRecCorrField;
            }
            set {
                this.resValRecCorrField = value;
            }
        }
        
        /// <remarks/>
        public decimal resLOQ {
            get {
                return this.resLOQField;
            }
            set {
                this.resLOQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string labSubSampCode {
            get {
                return this.labSubSampCodeField;
            }
            set {
                this.labSubSampCodeField = value;
            }
        }
        
        /// <remarks/>
        public string progType {
            get {
                return this.progTypeField;
            }
            set {
                this.progTypeField = value;
            }
        }
        
        /// <remarks/>
        public string accredProc {
            get {
                return this.accredProcField;
            }
            set {
                this.accredProcField = value;
            }
        }
        
        /// <remarks/>
        public decimal resValRec {
            get {
                return this.resValRecField;
            }
            set {
                this.resValRecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValRecSpecified {
            get {
                return this.resValRecFieldSpecified;
            }
            set {
                this.resValRecFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sampD {
            get {
                return this.sampDField;
            }
            set {
                this.sampDField = value;
            }
        }
        
        /// <remarks/>
        public string EFSAProdCode {
            get {
                return this.eFSAProdCodeField;
            }
            set {
                this.eFSAProdCodeField = value;
            }
        }
        
        /// <remarks/>
        public string prodManuf {
            get {
                return this.prodManufField;
            }
            set {
                this.prodManufField = value;
            }
        }
        
        /// <remarks/>
        public string origFishAreaText {
            get {
                return this.origFishAreaTextField;
            }
            set {
                this.origFishAreaTextField = value;
            }
        }
        
        /// <remarks/>
        public string amType {
            get {
                return this.amTypeField;
            }
            set {
                this.amTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class dataset {
        
        private result[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("result")]
        public result[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
}
