//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace EFSAMessageCreator_Pesticides {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class message {
        
        private object headerField;
        
        private payload payloadField;
        
        /// <remarks/>
        public object header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public payload payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSDRepeatableType {
        
        private string[] valueField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSDCompoundType {
        
        private string baseField;
        
        private SSDCompoundTypeValue[] valueField;
        
        private string[] textField;
        
        /// <remarks/>
        public string @base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value")]
        public SSDCompoundTypeValue[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SSDCompoundTypeValue {
        
        private string codeField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class payload {
        
        private object operationField;
        
        private result[] datasetField;
        
        /// <remarks/>
        public object operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public result[] dataset {
            get {
                return this.datasetField;
            }
            set {
                this.datasetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class result {
        
        private string localOrgIdField;
        
        private string localOrgCountryField;
        
        private string progIdField;
        
        private string progLegalRefField;
        
        private string sampStrategyField;
        
        private string progTypeField;
        
        private string sampMethodField;
        
        private string samplerField;
        
        private string sampPointField;
        
        private string sampEventIdField;
        
        private string sampUnitTypeField;
        
        private decimal sampUnitSizeField;
        
        private bool sampUnitSizeFieldSpecified;
        
        private string sampUnitSizeUnitField;
        
        private string sampIdField;
        
        private string repCountryField;
        
        private string sampCountryField;
        
        private string sampAreaField;
        
        private string repYearField;
        
        private string sampYField;
        
        private string sampMField;
        
        private string sampDField;
        
        private decimal sampSizeField;
        
        private bool sampSizeFieldSpecified;
        
        private string sampSizeUnitField;
        
        private string sampMatTypeField;
        
        private string sampMatTextField;
        
        private string origCountryField;
        
        private string origAreaField;
        
        private string origFishAreaCodeField;
        
        private string origFishAreaTextField;
        
        private string procCountryField;
        
        private string procAreaField;
        
        private string sampAnIdField;
        
        private string sampAnRefTimeField;
        
        private string analysisYField;
        
        private string analysisMField;
        
        private string analysisDField;
        
        private string anMatTextField;
        
        private string anPortSeqField;
        
        private decimal anPortSizeField;
        
        private bool anPortSizeFieldSpecified;
        
        private string anPortSizeUnitField;
        
        private string isolIdField;
        
        private string isolParamTextField;
        
        private string labIdField;
        
        private string labAccredField;
        
        private string labCountryField;
        
        private string paramTypeField;
        
        private string paramTextField;
        
        private string anMethRefIdField;
        
        private string anMethRefCodeField;
        
        private string anMethTypeField;
        
        private string anMethTextField;
        
        private string resIdField;
        
        private string accredProcField;
        
        private string resUnitField;
        
        private decimal resLODField;
        
        private bool resLODFieldSpecified;
        
        private decimal resLOQField;
        
        private decimal resLLWRField;
        
        private bool resLLWRFieldSpecified;
        
        private decimal resULWRField;
        
        private bool resULWRFieldSpecified;
        
        private decimal cCalphaField;
        
        private bool cCalphaFieldSpecified;
        
        private decimal cCbetaField;
        
        private bool cCbetaFieldSpecified;
        
        private decimal resValField;
        
        private bool resValFieldSpecified;
        
        private decimal resValRecField;
        
        private bool resValRecFieldSpecified;
        
        private string resValRecCorrField;
        
        private string exprResTypeField;
        
        private string resQualValueField;
        
        private string resTypeField;
        
        private decimal resValUncertField;
        
        private bool resValUncertFieldSpecified;
        
        private decimal resValUncertSDField;
        
        private bool resValUncertSDFieldSpecified;
        
        private decimal evalLowLimitField;
        
        private bool evalLowLimitFieldSpecified;
        
        private decimal evalHighLimitField;
        
        private bool evalHighLimitFieldSpecified;
        
        private string evalLimitTypeField;
        
        private string evalCodeField;
        
        private SSDRepeatableType actTakenCodeField;
        
        private SSDCompoundType localOrgInfoField;
        
        private SSDCompoundType progInfoField;
        
        private SSDCompoundType sampUnitIdsField;
        
        private SSDCompoundType sampEventInfoField;
        
        private SSDCompoundType sampInfoField;
        
        private SSDCompoundType sampMatCodeField;
        
        private SSDCompoundType sampMatInfoField;
        
        private SSDCompoundType sampAnInfoField;
        
        private SSDCompoundType anMatCodeField;
        
        private SSDCompoundType anMatInfoField;
        
        private SSDCompoundType anPortInfoField;
        
        private SSDCompoundType isolParamCodeField;
        
        private SSDCompoundType isolInfoField;
        
        private SSDCompoundType labInfoField;
        
        private SSDCompoundType paramCodeField;
        
        private SSDCompoundType anMethCodeField;
        
        private SSDCompoundType anMethInfoField;
        
        private SSDCompoundType exprResPercField;
        
        private SSDCompoundType resRefIdField;
        
        private SSDCompoundType resInfoField;
        
        private SSDCompoundType evalInfoField;
        
        private string amTypeField;
        
        /// <remarks/>
        public string localOrgId {
            get {
                return this.localOrgIdField;
            }
            set {
                this.localOrgIdField = value;
            }
        }
        
        /// <remarks/>
        public string localOrgCountry {
            get {
                return this.localOrgCountryField;
            }
            set {
                this.localOrgCountryField = value;
            }
        }
        
        /// <remarks/>
        public string progId {
            get {
                return this.progIdField;
            }
            set {
                this.progIdField = value;
            }
        }
        
        /// <remarks/>
        public string progLegalRef {
            get {
                return this.progLegalRefField;
            }
            set {
                this.progLegalRefField = value;
            }
        }
        
        /// <remarks/>
        public string sampStrategy {
            get {
                return this.sampStrategyField;
            }
            set {
                this.sampStrategyField = value;
            }
        }
        
        /// <remarks/>
        public string progType {
            get {
                return this.progTypeField;
            }
            set {
                this.progTypeField = value;
            }
        }
        
        /// <remarks/>
        public string sampMethod {
            get {
                return this.sampMethodField;
            }
            set {
                this.sampMethodField = value;
            }
        }
        
        /// <remarks/>
        public string sampler {
            get {
                return this.samplerField;
            }
            set {
                this.samplerField = value;
            }
        }
        
        /// <remarks/>
        public string sampPoint {
            get {
                return this.sampPointField;
            }
            set {
                this.sampPointField = value;
            }
        }
        
        /// <remarks/>
        public string sampEventId {
            get {
                return this.sampEventIdField;
            }
            set {
                this.sampEventIdField = value;
            }
        }
        
        /// <remarks/>
        public string sampUnitType {
            get {
                return this.sampUnitTypeField;
            }
            set {
                this.sampUnitTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal sampUnitSize {
            get {
                return this.sampUnitSizeField;
            }
            set {
                this.sampUnitSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sampUnitSizeSpecified {
            get {
                return this.sampUnitSizeFieldSpecified;
            }
            set {
                this.sampUnitSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string sampUnitSizeUnit {
            get {
                return this.sampUnitSizeUnitField;
            }
            set {
                this.sampUnitSizeUnitField = value;
            }
        }
        
        /// <remarks/>
        public string sampId {
            get {
                return this.sampIdField;
            }
            set {
                this.sampIdField = value;
            }
        }
        
        /// <remarks/>
        public string repCountry {
            get {
                return this.repCountryField;
            }
            set {
                this.repCountryField = value;
            }
        }
        
        /// <remarks/>
        public string sampCountry {
            get {
                return this.sampCountryField;
            }
            set {
                this.sampCountryField = value;
            }
        }
        
        /// <remarks/>
        public string sampArea {
            get {
                return this.sampAreaField;
            }
            set {
                this.sampAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string repYear {
            get {
                return this.repYearField;
            }
            set {
                this.repYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sampY {
            get {
                return this.sampYField;
            }
            set {
                this.sampYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sampM {
            get {
                return this.sampMField;
            }
            set {
                this.sampMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string sampD {
            get {
                return this.sampDField;
            }
            set {
                this.sampDField = value;
            }
        }
        
        /// <remarks/>
        public decimal sampSize {
            get {
                return this.sampSizeField;
            }
            set {
                this.sampSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sampSizeSpecified {
            get {
                return this.sampSizeFieldSpecified;
            }
            set {
                this.sampSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string sampSizeUnit {
            get {
                return this.sampSizeUnitField;
            }
            set {
                this.sampSizeUnitField = value;
            }
        }
        
        /// <remarks/>
        public string sampMatType {
            get {
                return this.sampMatTypeField;
            }
            set {
                this.sampMatTypeField = value;
            }
        }
        
        /// <remarks/>
        public string sampMatText {
            get {
                return this.sampMatTextField;
            }
            set {
                this.sampMatTextField = value;
            }
        }
        
        /// <remarks/>
        public string origCountry {
            get {
                return this.origCountryField;
            }
            set {
                this.origCountryField = value;
            }
        }
        
        /// <remarks/>
        public string origArea {
            get {
                return this.origAreaField;
            }
            set {
                this.origAreaField = value;
            }
        }
        
        /// <remarks/>
        public string origFishAreaCode {
            get {
                return this.origFishAreaCodeField;
            }
            set {
                this.origFishAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string origFishAreaText {
            get {
                return this.origFishAreaTextField;
            }
            set {
                this.origFishAreaTextField = value;
            }
        }
        
        /// <remarks/>
        public string procCountry {
            get {
                return this.procCountryField;
            }
            set {
                this.procCountryField = value;
            }
        }
        
        /// <remarks/>
        public string procArea {
            get {
                return this.procAreaField;
            }
            set {
                this.procAreaField = value;
            }
        }
        
        /// <remarks/>
        public string sampAnId {
            get {
                return this.sampAnIdField;
            }
            set {
                this.sampAnIdField = value;
            }
        }
        
        /// <remarks/>
        public string sampAnRefTime {
            get {
                return this.sampAnRefTimeField;
            }
            set {
                this.sampAnRefTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string analysisY {
            get {
                return this.analysisYField;
            }
            set {
                this.analysisYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string analysisM {
            get {
                return this.analysisMField;
            }
            set {
                this.analysisMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string analysisD {
            get {
                return this.analysisDField;
            }
            set {
                this.analysisDField = value;
            }
        }
        
        /// <remarks/>
        public string anMatText {
            get {
                return this.anMatTextField;
            }
            set {
                this.anMatTextField = value;
            }
        }
        
        /// <remarks/>
        public string anPortSeq {
            get {
                return this.anPortSeqField;
            }
            set {
                this.anPortSeqField = value;
            }
        }
        
        /// <remarks/>
        public decimal anPortSize {
            get {
                return this.anPortSizeField;
            }
            set {
                this.anPortSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anPortSizeSpecified {
            get {
                return this.anPortSizeFieldSpecified;
            }
            set {
                this.anPortSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string anPortSizeUnit {
            get {
                return this.anPortSizeUnitField;
            }
            set {
                this.anPortSizeUnitField = value;
            }
        }
        
        /// <remarks/>
        public string isolId {
            get {
                return this.isolIdField;
            }
            set {
                this.isolIdField = value;
            }
        }
        
        /// <remarks/>
        public string isolParamText {
            get {
                return this.isolParamTextField;
            }
            set {
                this.isolParamTextField = value;
            }
        }
        
        /// <remarks/>
        public string labId {
            get {
                return this.labIdField;
            }
            set {
                this.labIdField = value;
            }
        }
        
        /// <remarks/>
        public string labAccred {
            get {
                return this.labAccredField;
            }
            set {
                this.labAccredField = value;
            }
        }
        
        /// <remarks/>
        public string labCountry {
            get {
                return this.labCountryField;
            }
            set {
                this.labCountryField = value;
            }
        }
        
        /// <remarks/>
        public string paramType {
            get {
                return this.paramTypeField;
            }
            set {
                this.paramTypeField = value;
            }
        }
        
        /// <remarks/>
        public string paramText {
            get {
                return this.paramTextField;
            }
            set {
                this.paramTextField = value;
            }
        }
        
        /// <remarks/>
        public string anMethRefId {
            get {
                return this.anMethRefIdField;
            }
            set {
                this.anMethRefIdField = value;
            }
        }
        
        /// <remarks/>
        public string anMethRefCode {
            get {
                return this.anMethRefCodeField;
            }
            set {
                this.anMethRefCodeField = value;
            }
        }
        
        /// <remarks/>
        public string anMethType {
            get {
                return this.anMethTypeField;
            }
            set {
                this.anMethTypeField = value;
            }
        }
        
        /// <remarks/>
        public string anMethText {
            get {
                return this.anMethTextField;
            }
            set {
                this.anMethTextField = value;
            }
        }
        
        /// <remarks/>
        public string resId {
            get {
                return this.resIdField;
            }
            set {
                this.resIdField = value;
            }
        }
        
        /// <remarks/>
        public string accredProc {
            get {
                return this.accredProcField;
            }
            set {
                this.accredProcField = value;
            }
        }
        
        /// <remarks/>
        public string resUnit {
            get {
                return this.resUnitField;
            }
            set {
                this.resUnitField = value;
            }
        }
        
        /// <remarks/>
        public decimal resLOD {
            get {
                return this.resLODField;
            }
            set {
                this.resLODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resLODSpecified {
            get {
                return this.resLODFieldSpecified;
            }
            set {
                this.resLODFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal resLOQ {
            get {
                return this.resLOQField;
            }
            set {
                this.resLOQField = value;
            }
        }
        
        /// <remarks/>
        public decimal resLLWR {
            get {
                return this.resLLWRField;
            }
            set {
                this.resLLWRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resLLWRSpecified {
            get {
                return this.resLLWRFieldSpecified;
            }
            set {
                this.resLLWRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal resULWR {
            get {
                return this.resULWRField;
            }
            set {
                this.resULWRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resULWRSpecified {
            get {
                return this.resULWRFieldSpecified;
            }
            set {
                this.resULWRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CCalpha {
            get {
                return this.cCalphaField;
            }
            set {
                this.cCalphaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CCalphaSpecified {
            get {
                return this.cCalphaFieldSpecified;
            }
            set {
                this.cCalphaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal CCbeta {
            get {
                return this.cCbetaField;
            }
            set {
                this.cCbetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CCbetaSpecified {
            get {
                return this.cCbetaFieldSpecified;
            }
            set {
                this.cCbetaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal resVal {
            get {
                return this.resValField;
            }
            set {
                this.resValField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValSpecified {
            get {
                return this.resValFieldSpecified;
            }
            set {
                this.resValFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal resValRec {
            get {
                return this.resValRecField;
            }
            set {
                this.resValRecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValRecSpecified {
            get {
                return this.resValRecFieldSpecified;
            }
            set {
                this.resValRecFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string resValRecCorr {
            get {
                return this.resValRecCorrField;
            }
            set {
                this.resValRecCorrField = value;
            }
        }
        
        /// <remarks/>
        public string exprResType {
            get {
                return this.exprResTypeField;
            }
            set {
                this.exprResTypeField = value;
            }
        }
        
        /// <remarks/>
        public string resQualValue {
            get {
                return this.resQualValueField;
            }
            set {
                this.resQualValueField = value;
            }
        }
        
        /// <remarks/>
        public string resType {
            get {
                return this.resTypeField;
            }
            set {
                this.resTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal resValUncert {
            get {
                return this.resValUncertField;
            }
            set {
                this.resValUncertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValUncertSpecified {
            get {
                return this.resValUncertFieldSpecified;
            }
            set {
                this.resValUncertFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal resValUncertSD {
            get {
                return this.resValUncertSDField;
            }
            set {
                this.resValUncertSDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resValUncertSDSpecified {
            get {
                return this.resValUncertSDFieldSpecified;
            }
            set {
                this.resValUncertSDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal evalLowLimit {
            get {
                return this.evalLowLimitField;
            }
            set {
                this.evalLowLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool evalLowLimitSpecified {
            get {
                return this.evalLowLimitFieldSpecified;
            }
            set {
                this.evalLowLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal evalHighLimit {
            get {
                return this.evalHighLimitField;
            }
            set {
                this.evalHighLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool evalHighLimitSpecified {
            get {
                return this.evalHighLimitFieldSpecified;
            }
            set {
                this.evalHighLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string evalLimitType {
            get {
                return this.evalLimitTypeField;
            }
            set {
                this.evalLimitTypeField = value;
            }
        }
        
        /// <remarks/>
        public string evalCode {
            get {
                return this.evalCodeField;
            }
            set {
                this.evalCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDRepeatableType actTakenCode {
            get {
                return this.actTakenCodeField;
            }
            set {
                this.actTakenCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType localOrgInfo {
            get {
                return this.localOrgInfoField;
            }
            set {
                this.localOrgInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType progInfo {
            get {
                return this.progInfoField;
            }
            set {
                this.progInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType sampUnitIds {
            get {
                return this.sampUnitIdsField;
            }
            set {
                this.sampUnitIdsField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType sampEventInfo {
            get {
                return this.sampEventInfoField;
            }
            set {
                this.sampEventInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType sampInfo {
            get {
                return this.sampInfoField;
            }
            set {
                this.sampInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType sampMatCode {
            get {
                return this.sampMatCodeField;
            }
            set {
                this.sampMatCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType sampMatInfo {
            get {
                return this.sampMatInfoField;
            }
            set {
                this.sampMatInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType sampAnInfo {
            get {
                return this.sampAnInfoField;
            }
            set {
                this.sampAnInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType anMatCode {
            get {
                return this.anMatCodeField;
            }
            set {
                this.anMatCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType anMatInfo {
            get {
                return this.anMatInfoField;
            }
            set {
                this.anMatInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType anPortInfo {
            get {
                return this.anPortInfoField;
            }
            set {
                this.anPortInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType isolParamCode {
            get {
                return this.isolParamCodeField;
            }
            set {
                this.isolParamCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType isolInfo {
            get {
                return this.isolInfoField;
            }
            set {
                this.isolInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType labInfo {
            get {
                return this.labInfoField;
            }
            set {
                this.labInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType paramCode {
            get {
                return this.paramCodeField;
            }
            set {
                this.paramCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType anMethCode {
            get {
                return this.anMethCodeField;
            }
            set {
                this.anMethCodeField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType anMethInfo {
            get {
                return this.anMethInfoField;
            }
            set {
                this.anMethInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType exprResPerc {
            get {
                return this.exprResPercField;
            }
            set {
                this.exprResPercField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType resRefId {
            get {
                return this.resRefIdField;
            }
            set {
                this.resRefIdField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType resInfo {
            get {
                return this.resInfoField;
            }
            set {
                this.resInfoField = value;
            }
        }
        
        /// <remarks/>
        public SSDCompoundType evalInfo {
            get {
                return this.evalInfoField;
            }
            set {
                this.evalInfoField = value;
            }
        }
        
        /// <remarks/>
        public string amType {
            get {
                return this.amTypeField;
            }
            set {
                this.amTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class dataset {
        
        private result[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("result")]
        public result[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
}
